# 1. Proxy pour le Backend (évite les erreurs CORS)
[[redirects]]
  from = "/api/*"
  to = "https://nineat3a.onrender.com"
  status = 200
  force = true

# 2. Gestion du Routage React (évite les erreurs 404 au rafraîchissement)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200